# Generated by Django 4.2 on 2026-05-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vossai_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
